services:
  db:
    image: "postgres:16.3-alpine3.20"
    environment:
      POSTGRES_PASSWORD: "postgres123"
    volumes:
      - "$PWD/.local/postgres:/var/lib/postgresql/data"
    ports:
    - '5432:5432'
