services:
  db:
    image: "postgres:16.3-alpine3.20"
    environment:
      POSTGRES_PASSWORD: "postgres123"
    volumes:
      - "pg-data:/var/lib/postgresql/data"
    ports:
    - '5432:5432'

volumes:
  pg-data: {}
