"""add rule sponsor

Revision ID: 06b43d0625b9
Revises: 41264d466ae5
Create Date: 2024-08-13 16:52:44.727728

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '06b43d0625b9'
down_revision = '41264d466ae5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule', sa.Column('sponsor_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('rule', sa.Column('sponsor_image_data', sa.LargeBinary(), nullable=True))
    op.add_column('rule', sa.Column('sponsor_image_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('rule', sa.Column('prize', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule', 'prize')
    op.drop_column('rule', 'sponsor_image_type')
    op.drop_column('rule', 'sponsor_image_data')
    op.drop_column('rule', 'sponsor_name')
    # ### end Alembic commands ###
