"""Add title to notification

Revision ID: 3741e36575e8
Revises: 1dab4ef757ef
Create Date: 2024-11-22 10:59:31.937192

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '3741e36575e8'
down_revision = '1dab4ef757ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'title')
    # ### end Alembic commands ###
