"""many-to-many between Rule and ConsoleAchievement

Revision ID: 41264d466ae5
Revises: e711f8cc570a
Create Date: 2024-08-12 12:02:23.276293

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '41264d466ae5'
down_revision = 'e711f8cc570a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ruleconsoleachievement',
    sa.Column('rule_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ca_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['ca_slug'], ['consoleachievement.slug'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ),
    sa.PrimaryKeyConstraint('rule_id', 'ca_slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ruleconsoleachievement')
    # ### end Alembic commands ###
