"""empty message

Revision ID: e711f8cc570a
Revises: e6d7cfa8bcaf
Create Date: 2024-08-02 22:42:53.724987

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e711f8cc570a'
down_revision = 'e6d7cfa8bcaf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consoleachievement', sa.Column('image_data', sa.LargeBinary(), nullable=True))
    op.add_column('consoleachievement', sa.Column('image_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consoleachievement', 'image_type')
    op.drop_column('consoleachievement', 'image_data')
    # ### end Alembic commands ###
